# Generated by Django 6.0.2 on 2026-02-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('play', 'Play'), ('sleep', 'Sleep'), ('food', 'Food'), ('affection', 'Affection'), ('destruction', 'Destruction'), ('exploration', 'Exploration'), ('weird', 'Weird'), ('observation', 'Observation'), ('territory', 'Territory')], max_length=30)),
                ('energy_cost', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
