# Generated by Django 6.0.2 on 2026-04-17 15:06

from django.db import migrations

def seed_activities(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')

    activities = [
        {
            'name': 'Chasing the red laser',
            'category': 'play',
            'energy_cost': 3,
            'description': 'A high-speed chase across the entire house in pursuit of the mysterious red dot. Includes sliding, jumping, and dramatic turns.',
        },
        {
            'name': 'Attacking a toy mouse',
            'category': 'play',
            'energy_cost': 2,
            'description': 'A tactical ambush on a plush toy mouse, complete with stalking, pouncing, and repeated victorious bites.',
        },
        {
            'name': 'Midnight zoomies',
            'category': 'play',
            'energy_cost': 3,
            'description': 'Sudden explosive sprinting from room to room at 3 AM for absolutely no visible reason.',
        },
        {
            'name': 'Playing with a cardboard box',
            'category': 'play',
            'energy_cost': 1,
            'description': 'Entering, exiting, and dramatically defending a cardboard box as if it were a fortified castle.',
        },
        {
            'name': 'Sleeping on the keyboard',
            'category': 'sleep',
            'energy_cost': 1,
            'description': 'Strategically choosing the most inconvenient place possible to rest — usually during important work.',
        },
        {
            'name': 'Deep couch hibernation',
            'category': 'sleep',
            'energy_cost': 1,
            'description': 'A long, immovable sleep session buried in cushions like a furry loaf of bread.',
        },
        {
            'name': 'Eating wet food',
            'category': 'food',
            'energy_cost': 1,
            'description': 'Focused and enthusiastic consumption of gourmet canned delicacy.',
        },
        {
            'name': 'Demanding food loudly',
            'category': 'food',
            'energy_cost': 2,
            'description': 'Persistent and dramatic vocal performance in front of the food bowl until demands are met.',
        },
        {
            'name': 'Stealing food from the table',
            'category': 'food',
            'energy_cost': 2,
            'description': 'A sneaky operation involving timing, precision, and zero remorse.',
        },
        {
            'name': 'Sitting on owner\'s lap',
            'category': 'affection',
            'energy_cost': 1,
            'description': 'Claiming human lap territory and activating the purring engine.',
        },
        {
            'name': 'Head-bumping human',
            'category': 'affection',
            'energy_cost': 1,
            'description': 'A gentle forehead nudge as a sign of ownership and affection.',
        },
        {
            'name': 'Purring loudly',
            'category': 'affection',
            'energy_cost': 1,
            'description': 'A deep rumbling sound expressing comfort, happiness, or strategic manipulation.',
        },
        {
            'name': 'Bringing a \'gift\'',
            'category': 'affection',
            'energy_cost': 2,
            'description': 'Delivering a toy, sock, or unexpected prey as a thoughtful offering.',
        },
        {
            'name': 'Scratching the sofa',
            'category': 'destruction',
            'energy_cost': 1,
            'description': 'Sharpening claws on premium furniture despite the existence of a scratching post.',
        },
        {
            'name': 'Knocking objects off table',
            'category': 'destruction',
            'energy_cost': 1,
            'description': 'Slowly pushing items off surfaces while maintaining eye contact.',
        },
        {
            'name': 'Destroying toilet paper',
            'category': 'destruction',
            'energy_cost': 2,
            'description': 'Transforming a full toilet roll into snowy indoor chaos.',
        },
        {
            'name': 'Biting charger cables',
            'category': 'destruction',
            'energy_cost': 1,
            'description': 'Testing the durability of suspicious electronic snakes.',
        },
        {
            'name': 'Exploring a new room',
            'category': 'exploration',
            'energy_cost': 2,
            'description': 'Thorough inspection of unfamiliar territory with cautious stepping and intense sniffing.',
        },
        {
            'name': 'Sniffing grocery bags',
            'category': 'exploration',
            'energy_cost': 1,
            'description': 'Investigating fresh arrivals to ensure no threats (or treats) were smuggled in.',
        },
        {
            'name': 'Balcony patrol',
            'category': 'exploration',
            'energy_cost': 1,
            'description': 'Watching over the outside world like a vigilant guardian of the building.',
        },
        {
            'name': 'Inspecting closet contents',
            'category': 'exploration',
            'energy_cost': 2,
            'description': 'Diving into newly opened closets to investigate hidden realms.',
        },
        {
            'name': 'Staring at nothing',
            'category': 'weird',
            'energy_cost': 1,
            'description': 'Fixating intensely on a complete void for an uncomfortable amount of time.',
        },
        {
            'name': 'Random 3AM scream',
            'category': 'weird',
            'energy_cost': 2,
            'description': 'An unexpected nighttime vocal performance that wakes the entire household.',
        },
        {
            'name': 'Sudden backflip',
            'category': 'weird',
            'energy_cost': 3,
            'description': 'A spontaneous acrobatic move executed without warning or context.',
        },
        {
            'name': 'Sleeping in impossible positions',
            'category': 'weird',
            'energy_cost': 1,
            'description': 'Resting in a pose that defies basic anatomy and physics.',
        },
        {
            'name': 'Judging the human silently',
            'category': 'observation',
            'energy_cost': 1,
            'description': 'Maintaining prolonged eye contact as if evaluating life decisions.',
        },
        {
            'name': 'Watching birds from window',
            'category': 'observation',
            'energy_cost': 1,
            'description': 'Intense chirping and tail twitching while observing birds from indoors.',
        },
        {
            'name': 'Doorway surveillance',
            'category': 'observation',
            'energy_cost': 1,
            'description': 'Sitting in doorways to monitor movements and assert authority.',
        },
        {
            'name': 'Claiming a cardboard box',
            'category': 'territory',
            'energy_cost': 1,
            'description': 'Establishing dominance over an empty box and refusing relocation.',
        },
        {
            'name': 'Blocking hallway passage',
            'category': 'territory',
            'energy_cost': 1,
            'description': 'Strategically positioning body in narrow spaces to control traffic.',
        },
        {
            'name': 'Sitting on laptop',
            'category': 'territory',
            'energy_cost': 1,
            'description': 'Reclaiming warm electronics as personal property.',
        },
        {
            'name': 'Guarding food bowl',
            'category': 'territory',
            'energy_cost': 2,
            'description': 'Protecting the food supply from imaginary competitors.',
        },
    ]

    for activity_data in activities:
        Activity.objects.update_or_create(
            name=activity_data['name'],
            defaults={
                'category': activity_data['category'],
                'energy_cost': activity_data['energy_cost'],
                'description': activity_data['description'],
            }
        )


def remove_activities(apps, schema_editor):
    Activity = apps.get_model('activities', 'Activity')
    Activity.objects.filter(
        name__in=[
            'Chase the red dot',
            'Take a royal nap',
            'Knock things off the table',
            'Stare out the window',
            'Demand food dramatically',
            'Zoom around the house',
            'Hide in a box',
            'Cuddle with a human',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_activity_created_at'),
    ]

    operations = [
        migrations.RunPython(seed_activities, remove_activities)
    ]
