# Generated by Django 6.0.2 on 2026-02-04 18:50

import django.db.models.deletion
import moods.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
        ('cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(validators=[moods.validators.date_validator])),
                ('mood', models.CharField(choices=[('happy', 'Happy'), ('sad', 'Sad'), ('sleepy', 'Sleepy'), ('dramatic', 'Dramatic'), ('chaotic', 'Chaotic'), ('irritated', 'Irritated'), ('cuddly', 'Cuddly'), ('alert', 'Alert')], max_length=30)),
                ('energy_level', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')])),
                ('personal_note', models.TextField(blank=True, null=True)),
                ('activities', models.ManyToManyField(blank=True, related_name='mood_entries', to='activities.activity')),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mood_entries', to='cats.cat')),
            ],
        ),
    ]
