# Generated by Django 6.0.2 on 2026-02-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('cats', '0001_initial'),
        ('moods', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='moodentry',
            constraint=models.UniqueConstraint(fields=('cat', 'date'), name='unique_cat_date_entry'),
        ),
    ]
