# Generated by Django 6.0.2 on 2026-02-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
        ('cats', '0001_initial'),
        ('moods', '0003_alter_moodentry_unique_cat_date_entry'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='moodentry',
            name='unique_cat_date_entry',
            constraint=models.UniqueConstraint(fields=('cat', 'date'), name='unique_cat_date_entry'),
        ),
    ]
