# Generated by Django 6.0.2 on 2026-04-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0004_alter_moodentry_unique_cat_date_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moodentry',
            options={'permissions': [('can_view_all_moods', 'Can view all mood entries')]},
        ),
    ]
