# Generated by Django 6.0.2 on 2026-04-14 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0005_alter_moodentry_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoodTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
