# Generated by Django 6.0.2 on 2026-04-14 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0006_moodtag'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='mood_entries', to='moods.moodtag'),
        ),
    ]
