# Generated by Django 6.0.2 on 2026-04-15 01:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0007_moodentry_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoodTag',
            new_name='DayTag',
        ),
        migrations.RenameField(
            model_name='moodentry',
            old_name='tags',
            new_name='day_tags',
        ),
    ]
