# Generated by Django 6.0.2 on 2026-04-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0005_remove_toy_toy_type'),
        ('moods', '0008_rename_moodtag_daytag_rename_tags_moodentry_day_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='moodentry',
            name='toys',
            field=models.ManyToManyField(blank=True, related_name='mood_entries', to='cats.toy'),
        ),
    ]
