# Generated by Django 6.0.2 on 2026-04-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0009_moodentry_toys'),
    ]

    operations = [
        migrations.AddField(
            model_name='daytag',
            name='icon',
            field=models.CharField(default='🐾', max_length=15),
            preserve_default=False,
        ),
    ]
