# Generated by Django 6.0.2 on 2026-04-16 18:32

from django.db import migrations


def seed_day_tags(apps, schema_editor):
    DayTag = apps.get_model('moods', 'DayTag')

    day_tags = [
        {'name': 'Rainy', 'icon': '🌧️', 'description': 'A gloomy, rainy day.'},
        {'name': 'Sunny', 'icon': '☀️', 'description': 'A bright and sunny day.'},
        {'name': 'Chill', 'icon': '🍃', 'description': 'A calm and relaxed day.'},
        {'name': 'Busy', 'icon': '📋', 'description': 'A full and active day.'},
        {'name': 'Cozy Day', 'icon': '🧶', 'description': 'A warm and cozy day.'},
        {'name': 'Play Day', 'icon': '🎾', 'description': 'A playful and energetic day.'},
        {'name': 'Fast-paced', 'icon': '💨', 'description': 'Fast rhythm day.'},
        {'name': 'Slow-paced', 'icon': '🐌', 'description': 'Slow rhythm day.'},
        {'name': 'Special', 'icon': '🌠', 'description': 'A special day.'},
        {'name': 'Eventful', 'icon': '🎢', 'description': 'A day with many events.'},
        {'name': 'Predictable', 'icon': '🔁', 'description': 'A predictable day.'},
        {'name': 'Unpredictable', 'icon': '🔀', 'description': 'An unpredictable day.'},
    ]

    for tag_data in day_tags:
        DayTag.objects.update_or_create(
            name=tag_data['name'],
            defaults={
                'icon': tag_data['icon'],
                'description': tag_data['description'],
            }
        )


def remove_day_tags(apps, schema_editor):
    DayTag = apps.get_model('moods', 'DayTag')
    DayTag.objects.filter(
        name__in=[
            'Rainy',
            'Sunny',
            'Chill',
            'Busy',
            'Cozy Day',
            'Play Day',
            'Fast-paced',
            'Slow-paced',
            'Special',
            'Eventful',
            'Predictable',
            'Unpredictable',
        ]
    ).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('moods', '0010_daytag_icon'),
    ]

    operations = [
        migrations.RunPython(seed_day_tags, remove_day_tags),
    ]
