# Generated by Django 6.0.2 on 2026-02-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('personality', models.CharField(choices=[('calm', 'Calm'), ('lazy', 'Lazy'), ('loving', 'Loving'), ('mischievous', 'Mischievous'), ('independent', 'Independent'), ('bad_tempered', 'Bad tempered'), ('curious', 'Curious'), ('fun', 'Fun')], default='calm', max_length=30)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='cats/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
