# Generated by Django 6.0.2 on 2026-04-12 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0002_cat_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'permissions': [('can_manage_cat_profiles', 'Can manage cat profiles')]},
        ),
    ]
