# Generated by Django 6.0.2 on 2026-04-14 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0003_alter_cat_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Toy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('toy_type', models.CharField(choices=[('ball', 'Ball'), ('mouse', 'Mouse'), ('feather', 'Feather'), ('box', 'Box'), ('laser', 'Laser'), ('plush', 'Plush'), ('string', 'String'), ('hair_tie', 'Hair Tie'), ('spring', 'Spring'), ('crinkle', 'Crinkle Toy'), ('bottle_cap', 'Bottle Cap'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='toys', to='cats.cat')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
