# Generated by Django 6.0.2 on 2026-04-15 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cats', '0004_toy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toy',
            name='toy_type',
        ),
    ]
